### ISSUE TITLE
Not sure if replace_all_in_place is safe

### ISSUE THREAD

**Issue by e00E** [cowprotocol/ethcontract-rs#148]
We have this function

```rust
fn replace_all_in_place(&mut self, from: &str, to: &str) -> bool {
        let len = from.len();
        if to.len() != len {
            panic!("mismatch length of from and to string");
        }

        let mut found = false;
        while let Some(start) = self.find(from) {
            let end = start + len;

            // NOTE(nlordell): safe since the to string is valid utf-8 and
            //   `str::len()` returns byte length and not character length
            let section = unsafe { self[start..end].as_bytes_mut() };
            section.copy_from_slice(to.as_bytes());

            found = true
        }

        found
    }
```

The comment is correct about the length but I am not sure if replacement operation satisfies the condition that all strings are valid utf8. I don't have a counter example but utf8 is not a trivial format so it could be possible.

It could be enough to assert that both strings are ascii or we could check for valid utf8 again after the replacement. It would be nice if it was possible without unsafe, but not sure.

Or its already correct to someone, that knows utf8 better.

**Comment by fleupold** [comment]
Good point. It would be great if we could do this without unsafe code somehow. Limiting to ASCII should be fine for smart contracts, right?

**Comment by e00E** [comment]
We could move out of the string into bytes, then do find and replace on the bytes and finally convert back to string which will do a utf8 validity check. That does not involve unsafe code.

**Comment by nlordell** [comment]
Interesting point. I assumed it would be safe since `str::find` is operating on UTF8, so the found position should be the start of a UTF8 codepoint and not be in the middle. Additionally `str::len()` operates on byte length and not char length so we should be safe in terms of verifying the memory bounds.

In order to assume ASCII, we would have to check if library names can have utf-8 characters in them, but I don't see why it wouldn't be supported. And, if it isn't supported, I imagine it is because of oversight and not a technical reason.

That being said, the current implementation is probably buggy in that I think it would always fail if there was a library name that uses multi-byte UTF8 codepoints, since we wouldn't be able to do an in-place string substitution in the first place.

**Comment by nlordell** [comment]
I tried to break it with things like UTF8 skin tones where a single glyph comes from multiple codepoints but was unable to: https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=04e5130c1f8cb4bcd0fff0c84ad5e4ad

Also the way unicode encodes bytes makes it, from what understand in my quick read up, searching UTF8 is just searching byte sequences as the encoding was done in a way that smaller UTF8 sequences are never found in larger ones.

**edit**: This is because of how the UTF8 marker bits work.

**Comment by e00E** [comment]
I have let `cargo fuzz` loose on this for a couple of hours which didn't a utf8 issue. That doesn't prove the code correct but it makes it less likely to be wrong. Would still be nice to have it obviously correct or not use unsafe.

**Comment by e00E** [comment]
I tried this a bit without unsafe. It becomes annoying because there is no `str::find` function on slices and I don't like having a dependency just for that. Reading your explanation for why this is safe does make sense to me so lets not over complicate it and just have a check at the end to make sure its still valid utf-8.

**Comment by fleupold** [comment]
I think it would be nice if we can get rid of all the unsafe code pieces in ethcontract-rs. It seems none of them are really needed and just a shortcut.

**Comment by nlordell** [comment]
I think this is the last `unsafe` block. We can add a `#[deny(unsafe)]` on the crate after we remove this one :).
