### ISSUE TITLE
Allow generating contract bindings from an `Artifact` without needing the source json

### ISSUE THREAD

**Issue by e00E** [cowprotocol/ethcontract-rs#170]
Currently, in order to create the contract bindings in ethcontract-generate we require the corresponding json because the json has to be included in the macro output so that the Artifact can be re-created from the macro output.

It would be nice to have this work when we have an Artifact but no json because this would be more general and make some unit tests easier. In order for this to work we would need to be able to serialize the Artifact.

**Comment by fleupold** [comment]
I might not understand the terminology "Artifact" correctly. I thought the json was the artifact? What exactly is the difference?

**Comment by e00E** [comment]
I mean `struct Artifact` in ethcontract. It is deserialized from the artifact json.

**Comment by nlordell** [comment]
Currently, we actually inject the JSON source of the artifact and then create an `ARTIFACT: ethcontract::common::Artifact` `lazy_static` constant that deserializes the JSON.

This is a problem, as @e00E pointed out, as `ethabi::Contract` type, the data representing the contract ABI, does not implement `Deserialize`, so the input to the contract code generation MUST be a JSON string, and can't be some typed data. What further compounds this issue is that we currently need the contract ABI at runtime (as the `web3` crate uses it for detokenizing the data returned from `eth_call`s) so we need to have some way of re-constructing the the typed contract ABI that was used for generating the contract code at runtime.

I think there are a few approaches here to eliminate the requirement of a JSON string:
1. Generate code that constructs the ABI in Rust code instead of parsing JSON
2. Implement `ethabi::Contract` to JSON serialization, or modify the current `Artifact` to be serializable
3. Remove runtime dependency on `ethabi::Contract`, and more specifically `ethabi::Function`

I actually really like option 3, but I'm now sure how feasible it is.

**Comment by taminomara** [comment]
Getting rid of `ethabi` dependency would require that we re-implement abi representation ourselves, which seems like a big and unnecessary task. We could implement serialization for `ethabi::Contract` in our crate and then make PR to `ethabi`. 

Alternatively, we can generate a hug literal.

I don't have any strong preference for either one.

**Comment by nlordell** [comment]
> We could implement serialization for ethabi::Contract in our crate and then make PR to ethabi.

Seeing as @vkgnosis and myself are now maintainers for the `ethabi` repo (albeit, quite inactive) I think we can just add the implementation directly to the crate.

**Comment by taminomara** [comment]
Oh, I didn't realise that. Ok then =)

**Comment by taminomara** [comment]
Merged to a feature branch, will be in master soon — see the parent task.
