### ISSUE TITLE
non-truffle deploys with just an ABI, how to manually specify?

### ISSUE THREAD

**Issue by wilbarnes** [cowprotocol/ethcontract-rs#297]
hello, 

how can i generate bindings with just the ABI or find a way to mock a truffle deploy (if generating with an abi isn't possible)?

below is the [MCD_JUG etherscan contract link](https://etherscan.io/address/0x19c0976f590D67707E62397C87829d896Dc0f1F1#code) that i was using just as an experiment:
```
ethcontract::contract!(
    "etherscan:0x19c0976f590D67707E62397C87829d896Dc0f1F1",
);
```

the error: 
```
error: contract artifact is missing a name, this can happen when using a source that does not provide a contract name such  as Etherscan; in this case the contract must be manually specified
```

thank you

**Comment by nlordell** [comment]
Hey,

I guess the error message isn't as clear as it could be.

The issue here is the code generation doesn't know what to call the generated contract type since a contract ABI does not specify a contract name which is what is usually used to determine what to call the generated `mod` and `struct`.

Fortunately the solution is simple:
```
ethcontract::contract!(
    "etherscan:0x19c0976f590D67707E62397C87829d896Dc0f1F1",
    contract = McdJug,
);
```

This will generate a code that looks a little like this:
```
mod mcd_jug {
    struct Contract { ... }
}
use mcd_jug::Contract as McdJug;
```

I hope this clarifies things!

**Comment by wilbarnes** [comment]
thanks for the prompt response, i gave that a try with this result:

```
  --> src/main.rs:8:1
   |
8  | / ethcontract::contract!(
9  | |     "etherscan:0x19c0976f590D67707E62397C87829d896Dc0f1F1",
10 | |     contract = McdJug,
11 | | );
   | |  ^
   | |  |
   | |__previous definition of `file` here
   |    duplicate definition
   |
   = note: this error originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)

error: aborting due to previous error
```

**Comment by nlordell** [comment]
Ah, looks like the smart contract has multiple `file` functions and Rust doesn't support function overloading. This is currently [a known issue](https://github.com/gnosis/ethcontract-rs/issues/9). There is, however, a workaround that involves manually renaming methods so that there are no more name collisions:

```rust
ethcontract::contract!(
    "etherscan:0x19c0976f590D67707E62397C87829d896Dc0f1F1",
    contract = McdJug,
    methods {
        file(bytes32, bytes32, uint) as file_up_to_you;
        file(bytes32, uint) as file_what_to_call;
        file(bytes32, address) as file_these_methods; // NOTE: one of these may be omitted, in which case it will be called `file`
    },
);
```

Feel free to way in on the discussion in the issue I linked above, as I don't yet have a nice solution for solving this problem.

There is an example that demonstrates this here: https://github.com/gnosis/ethcontract-rs/blob/master/examples/overloaded.rs

**Comment by wilbarnes** [comment]
ok cool, that solution works, so thank you again. i'll go ahead and close this and move to the existing issue.
